on:
  push:
    branches: [master, main]
    paths: '**/translate-en-messages.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout adamlui/python-utils
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/python-utils
          path: adamlui/python-utils

      - name: Init target repos
        id: init_repos
        run: |
          target_repos=("adamlui/userscripts" "adamlui/chatgpt-apps" "adamlui/autoclear-chatgpt-history" "adamlui/chatgpt-auto-continue" "adamlui/chatgpt-auto-refresh" "adamlui/chatgpt-infinity" "adamlui/chatgpt-widescreen" "adamlui/youtube-classic" "kudoai/bravegpt" "kudoai/duckduckgpt")
          echo "::set-output name=repos::${target_repos[@]}"

      - name: Push changes to target repos
        run: |
          target_repos=(${{ steps.init_repos.outputs.repos }})

          for repo in "${target_repos[@]}"; do
            echo "::group::Pushing changes to $repo"
            echo "Running: stefanzweifel/git-auto-commit-action@v4 with repository=$repo"

            # Clone the target repository
            git clone https://github.com/$repo.git $GITHUB_WORKSPACE/$repo

            # Run the git-auto-commit-action for each target repository
            echo "::set-env name=REPO_PATH::$GITHUB_WORKSPACE/$repo"
            echo "::set-env name=COMMIT_MESSAGE::${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/python-utils`]"
            echo "::set-env name=COMMIT_EMAIL::auto-sync@chatgptevo.com"
            echo "::set-env name=FILE_PATTERN::.eslintrc.js"

            - name: Run git-auto-commit-action
              uses: stefanzweifel/git-auto-commit-action@v4
              env:
                REPO_PATH: $GITHUB_WORKSPACE/$repo
                COMMIT_MESSAGE: ${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/python-utils`]
                COMMIT_EMAIL: auto-sync@chatgptevo.com
                FILE_PATTERN: .eslintrc.js

            echo "::endgroup::"
          done
