on:
  push:
    branches: [master, main]
    paths: '**/translate-en-messages.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout adamlui/python-utils
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/python-utils
          path: adamlui/python-utils
          fetch-depth: 2

      - name: Init target repos
        id: init_repos
        run: |
          target_repos=("adamlui/userscripts" "adamlui/chatgpt-apps" "adamlui/autoclear-chatgpt-history" "adamlui/chatgpt-auto-continue" "adamlui/chatgpt-auto-refresh" "adamlui/chatgpt-infinity" "adamlui/chatgpt-widescreen" "adamlui/youtube-classic" "kudoai/bravegpt" "kudoai/duckduckgpt")
          echo "::set-output name=repos::${target_repos[*]}"

      - name: Replace translate-en-messages.py in target repos
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SYNC_PAT }}
        run: |
          target_repos=(${{ steps.init_repos.outputs.repos }})

          for repo in "${target_repos[@]}"; do
            if [[ "$repo" != "adamlui/python-utils" ]]; then
              echo "::group::Replacing translate-en-messages.py in $repo"
              git clone https://github.com/$repo.git $GITHUB_WORKSPACE/$repo
              cd $GITHUB_WORKSPACE/$repo
              git fetch --depth=2 origin # Fetching with a deeper history
              git remote set-url --push origin https://auto-sync-bot:$GITHUB_TOKEN@github.com/$repo
              find . -name "translate-en-messages.py" -exec sed -i 's|adamlui/userscripts/translate-en-messages.py|$repo/translate-messages/translate-en-messages.py|g' {} \;
              git add .
              git diff-index --quiet HEAD || git commit -m "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/python-utils`]" --author "auto-sync@kudoai.com" && git push --force
              echo "::endgroup::"
            fi
          done
