on:
  push:
    branches: [master, main]
    paths: '**/translate-en-messages.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout adamlui/python-utils
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/python-utils
          path: adamlui/python-utils

      - name: Init target repos
        id: init_repos
        run: |
          target_repos=("adamlui/userscripts" "adamlui/chatgpt-apps" "adamlui/autoclear-chatgpt-history" "adamlui/chatgpt-auto-continue" "adamlui/chatgpt-auto-refresh" "adamlui/chatgpt-infinity" "adamlui/chatgpt-widescreen" "adamlui/youtube-classic" "kudoai/bravegpt" "kudoai/duckduckgpt")
          echo "::set-output name=repos::${target_repos[@]}"

      - name: Checkout target repositories
        run: |
          repositories=(${{ steps.init_repos.outputs.repos }})
          for repo in "${repositories[@]}"; do
            repo_path=$(echo "$repo" | sed 's/\//_/g')
            echo "::group::Checking out $repo"
            echo "Running: git clone https://github.com/$repo.git $GITHUB_WORKSPACE/$repo_path"
            git clone https://github.com/$repo.git $GITHUB_WORKSPACE/$repo_path
            echo "::endgroup::"
          done

      - name: Sync translate-en-messages.py to all checked out repos
        run: |
          repositories=(${{ steps.init_repos.outputs.repos }})

          for repo in "${repositories[@]}"; do
            # Exclude the triggering repository
            if [[ "$repo" != "adamlui/python-utils" ]]; then
              repo_path=$(echo "$repo" | sed 's/\//_/g')
              cd "$GITHUB_WORKSPACE/$repo_path"
              find . -name "translate-en-messages.py" -print0 | while IFS= read -r -d $'\0' file; do
                new_path="${repo//\//\\/}/translate-messages/translate-en-messages.py"
                sed -i "s|adamlui/userscripts/translate-en-messages.py|$new_path|g" "$file"
                git add "$file"
              done

              # Commit and push changes only if replacements occurred
              git diff-index --quiet HEAD || git commit -m "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/python-utils`]" --author "auto-sync@kudoai.com"
              git push origin HEAD
            fi
          done
