on:
  push:
    branches: [master, main]
    paths: '**/translate-en-messages.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout adamlui/python-utils
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/python-utils
          path: adamlui/python-utils

      - name: Init target repos
        id: init_repos
        run: |
          target_repos=("adamlui/userscripts" "adamlui/chatgpt-apps" "adamlui/autoclear-chatgpt-history" "adamlui/chatgpt-auto-continue" "adamlui/chatgpt-auto-refresh" "adamlui/chatgpt-infinity" "adamlui/chatgpt-widescreen" "adamlui/youtube-classic" "kudoai/bravegpt" "kudoai/duckduckgpt")
          echo "::set-output name=repos::${target_repos[@]}" > target_repos.txt

      - name: Push changes to target repos
        run: |
          target_repos=(${{ steps.init_repos.outputs.repos }})

          for repo in "${target_repos[@]}"; do
            echo "::group::Pushing changes to $repo"
            echo "Running: stefanzweifel/git-auto-commit-action@v4 with repository=$repo"

            # Clone the target repository
            git clone https://github.com/$repo.git $GITHUB_WORKSPACE/$repo

            # Set the repository as the working directory
            cd $GITHUB_WORKSPACE/$repo

            # Run the git-auto-commit-action for each target repository
            echo "COMMIT_MESSAGE='${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/python-utils`]'" >> $GITHUB_ENV
            echo "COMMIT_EMAIL=auto-sync@chatgptevo.com" >> $GITHUB_ENV
            echo "FILE_PATTERN=**" >> $GITHUB_ENV

            # Run the git-auto-commit-action for each target repository
            echo "::set-output name=needs-commit::$(echo 'true')"

            echo "::endgroup::"
          done

      - name: Commit and push changes in target repos
        run: |
          target_repos=(${{ steps.init_repos.outputs.repos }})

          for repo in "${target_repos[@]}"; do
            if [[ "$repo" != "adamlui/python-utils" ]]; then
              echo "::group::Committing and pushing changes in $repo"

              # Set the repository as the working directory
              cd $GITHUB_WORKSPACE/$repo

              # Commit and push changes if needed
              needs_commit=$(echo "::get-output name=needs-commit::")
              if [[ "$needs_commit" == "true" ]]; then
                git config user.email "auto-sync@chatgptevo.com"
                git config user.name "auto-sync"
                git add .
                git commit -m "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/python-utils`]"
                git push --force
              else
                echo "No changes to commit."
              fi

              echo "::endgroup::"
            fi
          done
