on:
  push:
    branches: [ master, main ]
    paths: '**/translate-en-messages.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/python-utils
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/python-utils
          path: adamlui/python-utils

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Checkout adamlui/autoclear-chatgpt-history
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/autoclear-chatgpt-history
          path: adamlui/autoclear-chatgpt-history

      - name: Checkout adamlui/chatgpt-auto-continue
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-auto-continue
          path: adamlui/chatgpt-auto-continue

      - name: Checkout adamlui/chatgpt-auto-refresh
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-auto-refresh
          path: adamlui/chatgpt-auto-refresh

      - name: Checkout adamlui/chatgpt-infinity
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-infinity
          path: adamlui/chatgpt-infinity

      - name: Checkout adamlui/chatgpt-widescreen
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-widescreen
          path: adamlui/chatgpt-widescreen

      - name: Checkout adamlui/youtube-classic
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/youtube-classic
          path: adamlui/youtube-classic

      - name: Checkout kudoai/bravegpt
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: kudoai/bravegpt
          path: kudoai/bravegpt

      - name: Checkout kudoai/duckduckgpt
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: kudoai/duckduckgpt
          path: kudoai/duckduckgpt

      - name: Sync translate-en-messages.py to all checked out repos
        run: |
          repositories=()

          # Extract repository names from previous checkout steps
          echo "$GITHUB_EVENT_PATH" | jq -r '.check_suite.pull_requests[].head.repo.full_name' | while IFS= read -r repo; do
            repositories+=("$repo")
          done

          for repo in "${repositories[@]}"; do
            # Exclude the triggering repository
            if [[ "$repo" != "adamlui/python-utils" ]]; then
              repo_path=$(echo "$repo" | sed 's/\//_/g')
              find "$GITHUB_WORKSPACE/$repo_path" -name "translate-en-messages.py" -print0 | while IFS= read -r -d $'\0' file; do
                new_path="${repo//\//\\/}/translate-messages/translate-en-messages.py"
                sed -i "s|adamlui/userscripts/translate-en-messages.py|$new_path|g" "$file"
                git -C "$GITHUB_WORKSPACE/$repo_path" add "$file"
              done

              # Commit and push changes only if replacements occurred
              git -C "$GITHUB_WORKSPACE/$repo_path" diff-index --quiet HEAD || git -C "$GITHUB_WORKSPACE/$repo_path" commit -m "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/python-utils`]" --author "auto-sync@kudoai.com"
              git -C "$GITHUB_WORKSPACE/$repo_path" push --force
            fi
          done
