on:
  push:
    branches: [master, main]
    paths: '**/translate-en-messages.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout adamlui/python-utils
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/python-utils
          path: adamlui/python-utils
          fetch-depth: 2

      - name: Init target repos
        id: init_repos
        run: |
          target_repos=("adamlui/userscripts" "adamlui/chatgpt-apps" "adamlui/autoclear-chatgpt-history" "adamlui/chatgpt-auto-continue" "adamlui/chatgpt-auto-refresh" "adamlui/chatgpt-infinity" "adamlui/chatgpt-widescreen" "adamlui/youtube-classic" "kudoai/bravegpt" "kudoai/duckduckgpt")
          echo "::set-output name=repos::${target_repos[*]}"

      - name: Replace translate-en-messages.py in target repos
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SYNC_PAT }}
        run: |
          target_repos=(${{ steps.init_repos.outputs.repos }})

          source_file="${{ github.workspace }}/adamlui/python-utils/translate-messages/translate-en-messages.py"
          source_timestamp=$(git log -1 --format="%ct" -- "$source_file")

          for repo in "${target_repos[@]}"; do
            if [[ "$repo" != "adamlui/python-utils" ]]; then
              echo "::group::Replacing translate-en-messages.py in $repo"
              target_dir="$GITHUB_WORKSPACE/$repo"
              mkdir -p "$target_dir"
              git clone https://github.com/$repo.git $target_dir
              cd $target_dir
              git fetch --depth=2 origin # fetching with a deeper history
              git remote set-url --push origin https://auto-sync-bot:$GITHUB_TOKEN@github.com/$repo

              target_files=$(find . -name "translate-en-messages.py" -type f)

              for target_file in $target_files; do
                target_timestamp=$(git log -1 --format="%ct" -- "$target_file")

                if [[ $source_timestamp -gt $target_timestamp ]]; then
                  cp -f "$source_file" "$target_file"
                  git add "$target_file"
                fi
              done

              git diff-index --quiet HEAD || git commit -m "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/python-utils`]" --author "auto-sync@kudoai.com" && git push --force
              echo "::endgroup::"
            fi
          done
