name: Publish to PyPI on new release

on:
  release:
    types: [published, edited]

jobs:
  publish:
    if: ${{ startsWith(github.event.release.tag_name, 'ai-personas') == false }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: 3.x
      - run: |
          TAG="${{ github.event.release.tag_name }}"
          PROJECT="${TAG%-*}"
          echo "PROJECT=$PROJECT" >> $GITHUB_ENV
      - run: pip install build
      - run: |
          pwd
          ls -la
          cd ${{ env.PROJECT }} && python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1.14
        with:
          packages-dir: ${{ env.PROJECT }}/dist
