name: Validate links on push + PR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linkinator:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: JustinBeckwith/linkinator-action@f62ba0c110a76effb2ee6022cc6ce4ab161085e3
        with:
          paths: "**/*.md"
          statusCodes: '{ "429": "skip" }'
          linksToSkip: "#(?:readme|L\d+(?:-L\d+)?)$"
